AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FMLaaS Core

Globals:
  Function:
    Timeout: 3
    Runtime: python3.7
    MemorySize: 128
    Environment:
      Variables:
        MODELS_BUCKET: fmlaas-models
        DEVICE_TABLE_NAME: fml_devices

Resources:
  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: "ID"
          AttributeType: "N"
        -
          AttributeName: "APIKey"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "ID"
          KeyType: "HASH"
        -
          AttributeName: "APIKey"
          KeyType: "RANGE"
      TableName: "fml_devices"

  ModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fmlaas-models

  S3PutObjectPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: S3PutObjectPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub "${ModelBucket.Arn}/*"

  RegisterDeviceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: register_device/
      Handler: app.lambda_handler
      FunctionName: RegisterDevice
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DevicesTable
      Events:
        RegisterDeviceApiEvent:
          Type: Api
          Properties:
            Path: /api/v1/device/register
            Method: post

  CreateGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_group/
      Handler: app.lambda_handler
      FunctionName: CreateGroup
      Events:
        CreateGroupApiEvent:
          Type: Api
          Properties:
            Path: /api/v1/create_group
            Method: post

  SubmitModelUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: submit_model_update/
      Handler: app.lambda_handler
      FunctionName: SubmitModelUpdate
      Policies:
        - AWSLambdaBasicExecutionRole
        - !Ref S3PutObjectPolicy
      Events:
        SubmitModelUpdateApiEvent:
          Type: Api
          Properties:
            Path: /api/v1/submit_model_update
            Method: post
