AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FMLaaS Core

Globals:
  Function:
    Runtime: python3.7
    Environment:
      Variables:
        MODELS_BUCKET: fmlaas-models
        GROUPS_TABLE_NAME: fl_groups_prod
        AGGREGATION_LAMBDA_FUNCTION_NAME: AggregateModels

Resources:
  # ------------ Api ------------
  FmlaasProdApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod


  # ------------ DynamoDB ------------
  GroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "ID"
          KeyType: "HASH"
      TableName: "fl_groups_prod"


  # ------------ S3 ------------
  ModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fmlaas-models


  # ------------ IAM ------------
  S3PutObjectPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: S3PutObjectPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub "${ModelBucket.Arn}/*"

  S3GetObjectPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: S3GetObjectPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub "${ModelBucket.Arn}/*"


  # ------------ Layers ------------
  FMLaaSCoreDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: core-sam-dependencies
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.7
      RetentionPolicy: Delete


  # ------------ Lambda ------------
  RegisterDeviceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: register_device/
      Handler: app.lambda_handler
      FunctionName: RegisterDevice
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
      Events:
        RegisterDeviceApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/device/register
            Method: post

  StartRoundFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: start_round/
      Handler: app.lambda_handler
      FunctionName: StartRound
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
      Events:
        StartRoundApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/round/start
            Method: post

  GetRoundFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: get_round/
      Handler: app.lambda_handler
      FunctionName: GetRound
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
      Events:
        GetRoundApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/round/get/{group_id}/{round_id}
            Method: get

  GetGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: get_group/
      Handler: app.lambda_handler
      FunctionName: GetGroup
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
      Events:
        GetGroupApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/group/get/{group_id}
            Method: get

  ModelUploadedFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: model_uploaded/
      Handler: app.lambda_handler
      FunctionName: ModelUploaded
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
      Events:
        ModelUploadedEvent:
          Type: S3
          Properties:
            Bucket: !Ref ModelBucket
            Events: s3:ObjectCreated:*

  GetRoundAggregateModelFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: get_round_aggregate_model/
      Handler: app.lambda_handler
      FunctionName: GetRoundAggregateModel
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
        - !Ref S3GetObjectPolicy
      Events:
        GetRoundAggregateModelApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/round/get/aggregate_model/{group_id}/{round_id}
            Method: get

  GetGroupInitialModelFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: get_group_initial_model/
      Handler: app.lambda_handler
      FunctionName: GetGroupInitialModel
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
        - !Ref S3GetObjectPolicy
      Events:
        GetGroupInitialModelApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/group/get/initial_model/{group_id}
            Method: get

  CreateGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: create_group/
      Handler: app.lambda_handler
      FunctionName: CreateGroup
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
      Events:
        CreateGroupApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/group/create
            Method: post

  DeleteGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: delete_group/
      Handler: app.lambda_handler
      FunctionName: DeleteGroup
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
      Events:
        DeleteGroupApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/group/delete
            Method: post

  IsDeviceActiveFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: is_device_active/
      Handler: app.lambda_handler
      FunctionName: IsDeviceActive
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
      Events:
        IsDeviceActiveApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/device/get/active/{group_id}/{device_id}
            Method: get

  GetGroupCurrentRoundIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: get_group_current_round_id/
      Handler: app.lambda_handler
      FunctionName: GetGroupCurrentRoundIdFunction
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
      Events:
        GetGroupCurrentRoundIdEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/group/get/current_round_id/{group_id}
            Method: get

  SubmitModelUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: submit_model_update/
      Handler: app.lambda_handler
      FunctionName: SubmitModelUpdate
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: fmlaas-models
      Events:
        SubmitModelUpdateApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/submit_model_update
            Method: post

  SubmitGroupInitialModelFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      CodeUri: submit_group_initial_model/
      Handler: app.lambda_handler
      FunctionName: SubmitGroupInitialModel
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
        - AWSLambdaBasicExecutionRole
        - !Ref S3PutObjectPolicy
      Events:
        SubmitGroupInitialModelApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/group/post/initial_model
            Method: post

  AggregateModelsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      MemorySize: 256
      CodeUri: aggregate_models/
      Handler: app.lambda_handler
      FunctionName: AggregateModels
      Layers:
        - !Ref FMLaaSCoreDependencyLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
        - !Ref S3GetObjectPolicy
        - !Ref S3PutObjectPolicy
      Events:
        AggregateModelsApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FmlaasProdApi
            Path: /v1/round/aggregate
            Method: post
